### PR TITLE
fix: never let Axum abort Ouroboros miniprotocols on HTTP client disconnect

### LINKED ISSUE #173: N2C connection no longer viable
Causes:
* #175 

## Context

Version 0.0.1 on mac mini, the user is seeing this.

```
INFO N2C connection to node was successfully established at socket: /Users/vargasmontero/Library/Application Support/Daedalus Mainnet/cardano-node.socket
2025-02-14T03:29:02.349443Z ERROR N2C connection no longer viable: /Users/vargasmontero/Library/Application Support/Daedalus Mainnet/cardano-node.socket, BlockfrostError: localstate::ClientError: attempted to send message while agency is theirs, Metrics { created: Instant { tv_sec: 8807, tv_nsec: 756061833 }, recycled: Some(Instant { tv_sec: 9266, tv_nsec: 564873541 }), recycle_count: 165 }
2025-02-14T03:29:42.663635Z  INFO N2C connection to node was successfully established at socket: /Users/vargasmontero/Library/Application Support/Daedalus Mainnet/cardano-node.socket
2025-02-14T03:35:33.141407Z ERROR N2C connection no longer viable: /Users/vargasmontero/Library/Application Support/Daedalus Mainnet/cardano-node.socket, BlockfrostError: localstate::ClientError: attempted to send message while agency is theirs, Metrics { created: Instant { tv_sec: 9311, tv_nsec: 150372625 }, recycled: Some(Instant { tv_sec: 9655, tv_nsec: 812460541 }), recycle_count: 85 }
2025-02-14T03:43:06.270521Z  INFO N2C connection to node was successfully established at socket: /Users/vargasmontero/Library/Application Support/Daedalus Mainnet/cardano-node.socket
2025-02-14T03:43:08.088898Z ERROR N2C connection no longer viable: /Users/vargasmontero/Library/Application Support/Daedalus Mainnet/cardano-node.socket, BlockfrostError: localstate::ClientError: attempted to send message while agency is theirs, Metrics { created: Instant { tv_sec: 9009, tv_nsec: 394637958 }, recycled: Some(Instant { tv_sec: 10113, tv_nsec: 547547375 }), recycle_count: 405 }
2025-02-14T03:44:06.838455Z  INFO N2C connection to node was successfully established at socket: /Users/vargasmontero/Library/Application Support/Daedalus Mainnet/cardano-node.socket
2025-02-14T03:58:21.828983Z  INFO N2C connection to node was successfully established at socket: /Users/vargasmontero/Library/Application Support/Daedalus Mainnet/cardano-node.socket
2025-02-14T03:58:51.287146Z ERROR N2C connection no longer viable: /Users/vargasmontero/Library/Application Support/Daedalus Mainnet/cardano-node.socket, BlockfrostError: localstate::ClientError: attempted to send message while agency is theirs, Metrics { created: Instant { tv_sec: 11030, tv_nsec: 326440166 }, recycled: Some(Instant { tv_sec: 11053, tv_nsec: 957813375 }), recycle_count: 6 }
2025-02-14T04:00:52.538211Z ERROR N2C connection no longer viable: /Users/vargasmontero/Library/Application Support/Daedalus Mainnet/cardano-node.socket, BlockfrostError: localstate::ClientError: attempted to send message while agency is theirs, Metrics { created: Instant { tv_sec: 10114, tv_nsec: 762263833 }, recycled: Some(Instant { tv_sec: 11180, tv_nsec: 239360125 }), recycle_count: 317 }
2025-02-14T04:00:52.632820Z  INFO N2C connection to node was successfully established at socket: /Users/vargasmontero/Library/Application Support/Daedalus Mainnet/cardano-node.socket
2025-02-14T04:04:34.102360Z  INFO N2C connection to node was successfully established at socket: /Users/vargasmontero/Library/Application Support/Daedalus Mainnet/cardano-node.socket
2025-02-14T04:27:40.068507Z ERROR N2C connection no longer viable: /Users/vargasmontero/Library/Application Support/Daedalus Mainnet/cardano-node.socket, BlockfrostError: localstate::ClientError: attempted to send message while agency is theirs, Metrics { created: Instant { tv_sec: 11402, tv_nsec: 602120833 }, recycled: Some(Instant { tv_sec: 12785, tv_nsec: 87122041 }), recycle_count: 351 }
2025-02-14T04:27:40.095534Z  INFO N2C connection to node was successfully established at socket: /Users/vargasmontero/Library/Application Support/Daedalus Mainnet/cardano-node.socket
```

### LINKED ISSUE #175: Too many open files
Caused by:
* #173

## Context

After a while running on my mac mini in oakhost, I get:

Image

The ulimit is small, it is set to 256, but still - we might not be closing some connections down?

### PR DESCRIPTION
**Pull request by michalrus**
Resolves #173

Resolves #175

## Context

Originally reported as:
* #173 

This is a good explanation – https://github.com/blockfrost/blockfrost-platform/issues/173#issuecomment-2666748539:
> * This happens on machines with high load average.
> * Then `GET /` takes a significant while.
> * But the requester doesn’t wait that long, and disconnects.
> * This results in **Axum cancelling the handling future**.
> * And that’s why our code never calls `client.send_release().await` from Pallas.
> * But the connection is returned to the pool in its `impl Drop`.
> * So the next time we try to use it, it’s in incorrect state (not released), and we try to acquire, and that’s an error, which eventually results in `N2C connection no longer viable`.

## Additional work included

I also added a few more gauges to better instrument the code, and understand what’s happening, and I think they will be useful in general, so I left them in.

### CODE REVIEW

File: src/api/metrics.rs [hunk 1]
```diff
@@ -1,28 +1,30 @@
...
 use tokio::sync::RwLock;
 
 pub async fn route(
-    Extension(prometheus_handle): Extension<Arc<RwLock<PrometheusHandle>>>,
-    Extension(config): Extension<Arc<Config>>,
+    Extension(prometheus_handle): Extension<Option<Arc<RwLock<PrometheusHandle>>>>,
 ) -> Result<impl IntoResponse, BlockfrostError> {
-    if !config.metrics {
-        return Err(BlockfrostError::not_found());
+    match prometheus_handle {
```
Comment (ginnun) [inline src/api/metrics.rs:11]: I have a fix for this, I am working on the tests. This is good for as a quick fix.

File: src/api/metrics.rs [hunk 2]
```diff
@@ -32,9 +34,31 @@ pub fn setup_metrics_recorder() -> Arc<RwLock<PrometheusHandle>> {
         "cardano_node_connections",
         "Number of currently open Cardano node N2C connections"
     );
-
-    // Otherwise it’s not present under `GET /metrics` if we start with a failing cardano-node:
     gauge!("cardano_node_connections").set(0);
 
+    describe_gauge!(
```
Comment (ginnun) [inline src/api/metrics.rs:39]: Thank you for the new metrics

File: src/api/root.rs [hunk 3]
```diff
@@ -15,8 +15,14 @@ pub async fn route(
     Extension(node): Extension<NodePool>,
 ) -> Result<impl IntoResponse, BlockfrostError> {
     let errors = vec![];
-    let mut node = node.get().await?;
-    let node_info = node.sync_progress().await?;
+
+    // XXX: Axum must not abort Ouroboros protocols in the middle, hence a separate Tokio task:
```
Comment (ginnun) [inline src/api/root.rs:19]: What does `XXX:`  stands for?

**Review by ginnun — CHANGES_REQUESTED** [review]
@michalrus Thank you for the great inspection here! 

I think we can have improvements in the future, some options that are unrelated to eachother:
- non-blocking http and reactive way of handling node communications
- an overseer or manager for those spawned tasks, so they are under control (orphanage etc)
- prevent axum to halt even the remote party cancels

Also, I think we should code or contribute to be safe even somehow  Ouroboros protocols gets aborted in the middle.

File: src/api/tx_submit.rs [hunk 4]
```diff
@@ -9,9 +10,22 @@ pub async fn route(
     // Allow only application/cbor content type
     validate_content_type(&headers, &["application/cbor"])?;
 
-    // Submit transaction
-    let mut node = node.get().await?;
-    let response = node.submit_transaction(body.as_ref()).await?;
+    // XXX: Axum must not abort Ouroboros protocols in the middle, hence a separate Tokio task:
+    let response = tokio::spawn(async move {
```
Comment (ginnun) [inline src/api/tx_submit.rs:14]: Humm, just asking: Should we not cancel the submission if remote party halts the request?

File: src/api/metrics.rs (hunk 1 above)
Comment (michalrus) [reply src/api/metrics.rs:11]: Ah, right! I had to include this to be able to see `GET /metrics` for my investigation, but your fix in:
* #182 

… is better. I tried to keep this one minimal in terms of LOC.

I'll resolve the conflict as soon as your PR gets merged.

File: src/api/root.rs (hunk 3 above)
Comment (michalrus) [reply src/api/root.rs:19]: 😅 I never checked, and always used it to denote something tricky. I.e. as a more important comment than usual comments. As in you have to watch out when changing code around it, or you’ll break it.

According to https://github.com/SAP/styleguides/issues/279#issuecomment-1192321729:

> * Probably popularized by a developer called Bill Joy in 1971, working on the Berkley Software Distribution (BSD)

**Comment by michalrus** [comment]
@ginnun, re:

> we should code or contribute to be safe even somehow Ouroboros protocols gets aborted in the middle

This is really hard to get right. I've been thinking about a few possible solutions. The problem is that:

1. Axum will cancel the handler once the HTTP client disconnects – it will just not run anything on the next `.await`.
    1. This is a good default, we could change it globally by introducing a middleware which spawns everything in a Tokio task, but I would recommend against it.
2. But Ouroboros expects us to run the client release ceremony once we’re done using a particular Ouroboros miniprotocol.
3. Pallas implements this cleanup ceremony as `async fn` – there’s no other way, TBH.
4. So we somehow have to trigger an `async fn` from a synchronous `fn Drop::drop` on the connection wrapper, where we don’t have access to the async runtime.
5. And the other problem is that this cleanup **must be guaranteed to happen before** this connection is given to the next handler from the Deadpool.

We could allow dirty connection states in the pool, and to the cleanup on next `recycle`. That’s one way, but more complicated than wrapping in a `tokio::spawn` which is guaranteed to _not_ be cancelled by Axum.

I have one more optimization of `GET /` in the next PR, so we’re only left with this `tokio::spawn` solution in `POST /tx/submit`.

The future endpoints will query indexer/DB, so they should be good to cancel at any point.

File: src/api/metrics.rs (hunk 1 above)
Comment (ginnun) [reply src/api/metrics.rs:11]: No worries, whoever gets there first!

**Comment by ginnun** [comment]
> I have one more optimization of `GET /` in the next PR, so we’re only left with this `tokio::spawn` solution in `POST /tx/submit`.
>
I think this should be OK, no one will argue that tx submissions should be cancellable by halting the HTTP connection.
> The future endpoints will query indexer/DB, so they should be good to cancel at any point.

Could you elaborate?

**Comment by michalrus** [comment]
> > The future endpoints will query indexer/DB, so they should be good to cancel at any point.
> 
> Could you elaborate?

Just an example, but I'm suspecting that, say, [`deadpool-postgres`](https://docs.rs/crate/deadpool-postgres/0.14.1) allows you to cancel the asynchronous execution at any point, and brings back the connection to a usable state (cancels any outstanding transactions etc.). The connection to Postgres is less fragile w.r.t. `ROLLBACK TRANSACTION` than our Ouroboros clients.

So it Just Works™, unlike here.

**Comment by ginnun** [comment]
@michalrus In the future, when we have the bandwidth and the will, we could at least keep the spawned tasks in a list/manager, so they are not 'orphans', at least in the name ^^. But this might be nitpicking, so secure to ignore.

**Review by ginnun — APPROVED** [review]
PR looks small, but the effort is huge!

**Comment by vladimirvolek** [comment]
Good work!
